version: '3.8'

services:

  # Run Rasa Pro with the inspector.
  assistant:
    image: europe-west3-docker.pkg.dev/rasa-releases/rasa-pro/rasa-pro:3.9.3
    environment:
      - SERVICE_FQDN_RASA_5005
    volumes:
      - .:/app
    command:
      - 'run'
    ports:
      - '5005:5005'
    env_file:
      - .env
    user: root

  tracker_store:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: rasa
      POSTGRES_USER: rasa
      POSTGRES_PASSWORD: rasa
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  # Run the action server.
  action_server:
    image: europe-west3-docker.pkg.dev/rasa-releases/rasa-pro/rasa-pro:3.9.3
    volumes:
      - .:/app
    command:
      - 'run'
      - 'actions'
    ports: 
      - '5055:5055'
    env_file:
      - .env
    user: root

volumes:
  db:
    driver: local
